Repository wp-cli/.github, pull requests merged in 2022-10, with the labels that each got.

#26 Add missing `WP_VERSION` to Behat precheck
  .github/workflows/testing.yml
  workflows/code-quality.yml
Labels: scope:testing

#27 Remove misplaced file
  workflows/code-quality.yml
Labels: bug

#28 Add `github-actions` ecosystem to dependabot config
  .github/dependabot.yml
Labels: enhancement
